### PR TITLE
BGP-30 -[frontend and backend] - Login page

### PR DESCRIPTION
**Pull request by ZichanYang324**
# Description
Add login page with front end and backend, also add UI from react material UI.

## Related PRS (if any):
please checkout to this PR #19  and test the register function, then start testing on this PR

## Main changes explained:
- Add redux for login employee client
- Add dashboard and Nav bar
- Add cookies
- Add token

## How to test:
1. check into current branch
2. do `cd Server` and separate another terminal do `cd Employee-Client`
3. do `npm install`  and `npm run dev` in both frontend and backend to run this PR locally
4. add routes `.../login`
5. verify function “login” with username and password

## Screenshots or videos of changes or expecting result:
Screenshot 2024-02-25 at 13 01 50
Screenshot 2024-02-25 at 13 01 57

## Note:
If you want to log in and then logout try another login, you will need to clear the cookies, sessions, and local storage(you can do this in the inspect -> application -> storage(clear these part, including cookies, sessions, and local storage)

### CODE REVIEW

**Review by XiangweiChen — APPROVED** [review]
Followed the testing instructions, and the frontend/backend for register and login work as expected with the provided environment credentials keys in Server. Good job!

**Review by christorange — APPROVED** [review]
LGTM!

**Review by christorange — COMMENTED** [review]
Will suggest some changes to `customFetch()`

**Comment by christorange** [comment]
I have only edited `useFetch()` code to add auth related logic to it, haven't touched and part using `customFetch` though, will do this in my future pr

**Review by yuelikestocode — APPROVED** [review]

**Pull request merged**
